-- Development Seed Data
-- Test users for local development

-- NOTE: These are TEST USERS with FAKE DATA
-- DO NOT use in production!

-- Test encryption key for development: Generate with
-- node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"

-- Test User 1: Restaurant Owner
-- Email: owner@test.com
-- Password: TestPass123
-- Note: Password hash and encrypted fields will be generated by the application

-- Test User 2: Manager
-- Email: manager@test.com
-- Password: TestPass123

-- Test User 3: Staff
-- Email: staff@test.com  
-- Password: TestPass123

-- ============================================
-- HOW TO USE THIS FILE
-- ============================================
-- 1. Use the User model to create test users:
--
--    const User = require('./database/models/User');
--    
--    await User.createUser({
--      name: 'Test Owner',
--      email: 'owner@test.com',
--      password: 'TestPass123',
--      phone: '+1234567890',
--      tenantId: null
--    });
--
-- 2. Or create a seed script:
--    node database/seeds/run-seeds.js
--
-- ============================================

-- DO NOT insert encrypted data directly!
-- Use the application layer to properly encrypt/hash data











